name: Add myself to the webring
description: Use this issue if you don't feel comfortable using git to add yourself.
title: "[Add webring member] "
labels: "addition"
assignees:
  - ericwbailey
body:
  - type: markdown
    attributes:
      value: |
        Don't feel comfortable using git? Filling out this form will help us add you to the webring.
  - type: input
    id: name
    attributes:
      label: Your name
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Your website URL
    validations:
      required: true
  - type: input
    id: linkedin
    attributes:
      label: Your LinkedIn profile URL
  - type: input
    id: mastodon
    attributes:
      label: Your Mastodon profile URL
  - type: input
    id: rss
    attributes:
      label: Your website's RSS feed URL
  - type: input
    id: twitter
    attributes:
      label: Your Twitter profile URL
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Any other information we should know about for this bug?
  - type: checkboxes
    id: added-code
    attributes:
      label: I have added the webring code to my website
      description: Please ensure [the webring code](https://a11y-webring.club/#list-the-webring-on-your-website) has been added to your site before submitting this issue.
      options:
        - label: I have added the webring code to my website
          required: true
  - type: checkboxes
    id: https
    attributes:
      label: HTTPS
      options:
        - label: My site uses the HTTPS protocol
          required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of conduct
      description: By submitting this issue, you agree to follow our [code of conduct](https://github.com/ericwbailey/a11y-webring.club/blob/main/.github/CODE_OF_CONDUCT.md#code-of-conduct)
      options:
        - label: I agree to follow this project's code of conduct
          required: true
